@baseUrl=http://localhost:3000/api
###
GET {{baseUrl}}/user/find-all HTTP/1.1
###
GET {{baseUrl}}/user/find-by-home HTTP/1.1
### # make paginated if possible
GET {{baseUrl}}/home/find-by-user HTTP/1.1
###
POST {{baseUrl}}/home/update-users HTTP/1.1